# Generated by Django 2.2 on 2020-11-05 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TeamAdmin', '0007_auto_20201103_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrenador',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rol',
        ),
        migrations.AddField(
            model_name='entrenador',
            name='useuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jugador',
            name='useuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='useuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
