# Generated by Django 2.2 on 2020-11-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamAdmin', '0009_auto_20201105_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
