# Generated by Django 2.2 on 2020-11-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamAdmin', '0010_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrenador',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
