# Generated by Django 2.2 on 2020-11-26 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
                ('apellido', models.CharField(default='', max_length=20)),
                ('dni', models.CharField(default='', max_length=20)),
                ('telefono', models.CharField(default='', max_length=20)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
                ('apellido', models.CharField(default='', max_length=20)),
                ('dni', models.CharField(default='', max_length=20)),
                ('telefono', models.CharField(default='', max_length=20)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamAdmin.Deporte')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('minuto', models.CharField(default='', max_length=20)),
                ('tiempo', models.CharField(default='', max_length=20)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamAdmin.Jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
                ('tipo', models.CharField(choices=[('e', 'Entrenamiento'), ('p', 'Partido'), ('r', 'Reunion de equipo')], default='e', max_length=15)),
                ('fecha', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('contrincante', models.CharField(blank=True, default='', max_length=20)),
                ('puntoContrincante', models.IntegerField(blank=True, default=0)),
                ('puntoEquipo', models.IntegerField(blank=True, default=None)),
                ('asistencia', models.ManyToManyField(default=None, to='TeamAdmin.Jugador')),
                ('punto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamAdmin.Punto')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamAdmin.Deporte')),
                ('entrenadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamAdmin.Entrenador')),
                ('jugadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamAdmin.Jugador')),
            ],
        ),
        migrations.AddField(
            model_name='deporte',
            name='posicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamAdmin.Posicion'),
        ),
    ]
