# Generated by Django 2.2 on 2020-10-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='punto',
        ),
        migrations.AddField(
            model_name='partido',
            name='punto',
            field=models.ManyToManyField(to='TeamAdmin.Punto'),
        ),
    ]
