# Generated by Django 2.2 on 2020-11-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamAdmin', '0002_auto_20201126_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='punto',
        ),
        migrations.RemoveField(
            model_name='tipo',
            name='entrenamiento',
        ),
        migrations.RemoveField(
            model_name='tipo',
            name='partido',
        ),
        migrations.AddField(
            model_name='evento',
            name='contrincante',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='evento',
            name='punto',
            field=models.ManyToManyField(blank=True, to='TeamAdmin.Punto'),
        ),
        migrations.AddField(
            model_name='evento',
            name='puntoContrincante',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='evento',
            name='puntoEquipo',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('e', 'Entrenamiento'), ('p', 'Partido'), ('r', 'Reunion de equipo')], default='e', max_length=15),
        ),
        migrations.DeleteModel(
            name='Entrenamiento',
        ),
        migrations.DeleteModel(
            name='Partido',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
