# Generated by Django 2.2 on 2020-10-15 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamAdmin', '0003_auto_20201015_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='asistencia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TeamAdmin.Jugador'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TeamAdmin.Tipo'),
        ),
    ]
