# Generated by Django 2.2 on 2020-11-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamAdmin', '0004_auto_20201126_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='asistencia',
        ),
        migrations.AddField(
            model_name='evento',
            name='asistencia',
            field=models.ManyToManyField(default=None, to='TeamAdmin.Jugador'),
        ),
    ]
