# Generated by Django 2.2 on 2020-11-26 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamAdmin', '0006_auto_20201126_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='punto',
        ),
        migrations.AddField(
            model_name='evento',
            name='punto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamAdmin.Punto'),
        ),
    ]
