# Generated by Django 2.2 on 2020-11-03 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TeamAdmin', '0006_remove_profile_nada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='apellido',
            field=models.CharField(default='', help_text='Apellido', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='', help_text='Email', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='nombre',
            field=models.CharField(default='', help_text='Nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='rol',
            field=models.CharField(default='', help_text='Apellido', max_length=100),
        ),
    ]
