# Generated by Django 2.2 on 2020-11-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamAdmin', '0008_auto_20201105_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
